
custom_chat.ok=OK
custom_chat.yes=是的
custom_chat.no=No
custom_chat.cancel=取消
custom_chat.id=ID
custom_chat.team=队伍
custom_chat.steamid=SteamID
custom_chat.invalid_input=无效输入
custom_chat.say=说...
custom_chat.team_say=说 (仅队伍)...
custom_chat.channel.global=全局
custom_chat.channel.team=仅队伍
custom_chat.channel.open_dm=发起私信
custom_chat.channel.close_dm=关闭私信
custom_chat.channel.dm_player_filter=搜寻玩家...
custom_chat.channel.no_dm_targets=没有可用的玩家!
custom_chat.copy_to_clipboard=复制到剪贴板
custom_chat.click_to_reveal=点击显示图片
custom_chat.category.custom=自定义
custom_chat.category.misc=杂项
custom_chat.category.people=人物
custom_chat.category.objects=物品
custom_chat.category.symbols=字符
custom_chat.category.nature=自然
custom_chat.category.places=交通
custom_chat.category.regional=字母
custom_chat.category.flags=旗帜
custom_chat.context.font_size=字体大小
custom_chat.context.theme=自定义主题...
custom_chat.context.reset=重置...
custom_chat.context.position=位置
custom_chat.context.size=尺寸
custom_chat.context.position_and_size=位置及尺寸
custom_chat.context.copy_link=复制链接
custom_chat.context.copy_text=复制文本
custom_chat.context.copy_steamid=复制SteamID
custom_chat.context.copy_steamid64=复制64位SteamID
custom_chat.context.open_profile=打开个人资料页面
custom_chat.context.clear_all=清除全部
custom_chat.context.emojis=[管理员] Emojis表情...
custom_chat.context.tags=[管理员] 聊天标签...
custom_chat.find=查找...
custom_chat.find_tip=输入要查找的文本
custom_chat.timestamps.enable=启用时间戳
custom_chat.timestamps.disable=禁用时间戳
custom_chat.whitelist.enable=阻止来自未知URL的图像
custom_chat.whitelist.disable=允许来自未知URL的图像
custom_chat.whitelist.enabled=白名单现在只会从受信任的网站加载图片！
custom_chat.whitelist.disabled=白名单现在允许来自任何的网站加载图片！
custom_chat.whitelist.allow_tip1=此选项将允许从任何URL加载图像.
custom_chat.whitelist.allow_tip2=这意味着无论它们来自哪个网站，你都会加载它们，它们也可以用来获取你的IP地址！
custom_chat.whitelist.allow_tip3=注意：这只影响自定义聊天的内置白名单，有些服务器可能有自己的白名单.
custom_chat.whitelist.allow_anyway=无论如何都允许
custom_chat.tab.team_tags=团队标签
custom_chat.tab.player_tags=特定玩家标签
custom_chat.tab.conn_disconn=连接/断开连接信息
custom_chat.tags.unavailable=为了避免与其他插件冲突，聊天标签被禁用！确保没有安装aTags.
custom_chat.tags.title=服务器聊天标签
custom_chat.tags.piece_tip=分别使用NAME_COL和MESSAGE_COL\n更改名称/消息\n颜色.
custom_chat.tags.text_placeholder=添加一段文字...
custom_chat.tags.add_piece=增加一部分
custom_chat.tags.remove_piece=移除一部分
custom_chat.tags.update_piece=升级一部分
custom_chat.tags.add_player=添加
custom_chat.tags.add_steamid=添加SteamID
custom_chat.tags.remove_steamid=移除SteamID
custom_chat.tags.invalid_steamid=无效的SteamID！
custom_chat.tags.steamid_already_in_use=SteamID已经在名单上了！
custom_chat.tags.show_join_messages=显示自定义连接消息
custom_chat.tags.join_prefix=进服前缀
custom_chat.tags.join_suffix=进服后缀
custom_chat.tags.join_color=进服玩家名字的颜色
custom_chat.tags.show_leave_messages=显示自定义断开消息
custom_chat.tags.leave_prefix=离开前缀
custom_chat.tags.leave_suffix=离开后缀
custom_chat.tags.leave_color=离开服务器的玩家名字的颜色
custom_chat.tags.apply=应用所有更改
custom_chat.tags.apply_query=此操作会将聊天标签和加入/离开消息应用到此服务器.你确定吗？
custom_chat.tags.show_bot_joinleave_messages=显示机器人的加入/离开消息
custom_chat.emojis.title=服务器Emojis表情
custom_chat.emojis.invalid=无效的Emoji表情
custom_chat.emojis.invalid_reason=无效的emoji (%d): %s
custom_chat.emojis.invalid_characters=只允许 _, -, 及0-9和A-Z之间的字符
custom_chat.emojis.empty_id=ID为空
custom_chat.emojis.id_in_use=Emoji表情 (%d) 已经使用相同的ID
custom_chat.emojis.id_builtin=这个ID "%s" 是为内置emoji保留的
custom_chat.emojis.url_placeholder=<URL to a image>
custom_chat.emojis.empty_url=URL为空
custom_chat.emojis.branch_warning=使用较新版本TLS协议（https，如Discord）的网站可能无法在没有Garry’s Mod的Chromium beta的情况下工作.
custom_chat.emojis.add=添加
custom_chat.emojis.add_silkicon=添加Silkicon
custom_chat.emojis.add_silkicon_tip=添加一个与GMod捆绑的图标
custom_chat.emojis.remove=移除
custom_chat.emojis.empty_list=还没有Emojis表情.
custom_chat.emojis.apply=接受
custom_chat.emojis.apply_title=设置自定义Emojis表情
custom_chat.emojis.apply_tip=此操作将为该服务器设置自定义Emojis表情.\n你确定吗？
custom_chat.emojis.remove_tip=此操作将删除此服务器上的所有自定义Emojis表情.\n你确定吗？
custom_chat.theme.customize_title=自定义主题
custom_chat.theme.no_edit=此主题无法自定义.
custom_chat.theme.default=[内置] 默认主题
custom_chat.theme.default_description=自定义聊天的默认主题
custom_chat.theme.server_default=[内置] 默认服务器主题
custom_chat.theme.server_default_description=您当前正在游玩的服务器的主题
custom_chat.theme.new_name=我的主题
custom_chat.theme.new_tip=请为您的新主题指定一个文件名.
custom_chat.theme.file_name_exists=这个文件名的主题已经存在！
custom_chat.theme.invalid_file_name=您的文件名无效或为空！
custom_chat.theme.new=新建
custom_chat.theme.delete=删除
custom_chat.theme.delete_tip=您确定要删除所选主题吗?
custom_chat.theme.export=导出
custom_chat.theme.export_title=导出主题
custom_chat.theme.export_tip=使用此代码与他人共享此主题.
custom_chat.theme.import=导入
custom_chat.theme.import_title=导入主题
custom_chat.theme.import_tip=将主题代码粘贴到这里.
custom_chat.theme.import_failed=导入失败
custom_chat.theme.import_error_invalid=无效的数据！
custom_chat.theme.import_error_empty=JSON数据为空！
custom_chat.theme.import_error_json=无效的JSON数据！
custom_chat.theme.name=名称
custom_chat.theme.description=描述
custom_chat.theme.font=字体
custom_chat.theme.font_custom=自定义字体
custom_chat.theme.font_custom_item=<自定义>
custom_chat.theme.font_custom_name=请输入所需的字体名称。
custom_chat.theme.font_shadow=字体阴影
custom_chat.theme.slide_animation=幻灯片动画
custom_chat.theme.avatars=玩家头像
custom_chat.theme.bg_blur=背景透明度
custom_chat.theme.corner_radius=角半径
custom_chat.theme.padding=填充
custom_chat.theme.color.bg=背景颜色
custom_chat.theme.color.input=输入文本颜色
custom_chat.theme.color.input_bg=输入背景颜色
custom_chat.theme.color.scroll_bar=滚动条颜色
custom_chat.theme.color.scroll_bg=滚动背景色
custom_chat.theme.color.highlight=选定文本背景颜色
custom_chat.theme.import_success=成功导入主题！
custom_chat.server_theme.set=设置服务端主题
custom_chat.server_theme.already_set=这个服务器已经有了一个主题。你要干什么？
custom_chat.server_theme.override=覆盖
custom_chat.server_theme.remove=移除
custom_chat.server_theme.tip=这个动作将迫使所有玩家(包括后来加入的玩家)使用这个主题。你确定吗？
custom_chat.friend_spawned1=你的好友
custom_chat.friend_spawned2=加入了.
custom_chat.took=耗时
custom_chat.last_seen1=加载，最后于
custom_chat.first_seen=加载，首次加入.
custom_chat.time.year=年
custom_chat.time.years=年
custom_chat.time.month=月
custom_chat.time.months=月
custom_chat.time.week=周
custom_chat.time.weeks=周
custom_chat.time.day=日
custom_chat.time.days=日
custom_chat.time.hour=时
custom_chat.time.hours=时
custom_chat.time.minute=分
custom_chat.time.minutes=分
custom_chat.time.second=秒
custom_chat.time.seconds=秒
custom_chat.last_seen2=前游玩.
custom_chat.server_dms_disabled=此服务器已禁用私信.
custom_chat.side_bar.show=显示侧边栏
custom_chat.side_bar.hide=隐藏侧边栏